[workspace]
members = ["kivis", "kivis-derive"]
exclude = ["fs-store"]
resolver = "2"

[workspace.package]
version = "0.2.1"

[workspace.dependencies]
kivis = { path = "kivis" }
kivis-derive = { path = "kivis-derive" }

serde = { version = "1.0.219", features = ["derive"] }
bincode = { version = "2.0.1", features = ["serde"] }
hex = "0.4.3"
