[workspace]
members = ["kivis", "kivis-derive"]
exclude = ["fs-store"]
resolver = "2"

[workspace.package]
version = "0.2.3"

[workspace.dependencies]
kivis = { path = "kivis" }
kivis-derive = { path = "kivis-derive", version = "0.2.2" }

serde = { version = "1.0.228", features = ["derive"] }
bincode = { version = "2.0.1", features = ["serde"] }
hex = "0.4.3"
paste = "1.0.15"
