[package]
name = "kivis-fs"
version = "0.1.0"
edition = "2024"

[dependencies]
kivis = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
hex = { workspace = true }
csv = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
