[package]
name = "kivis-fs"
version = "0.1.1"
edition = "2024"

[dependencies]
kivis = { workspace = true }
serde = { workspace = true }
hex = { workspace = true }
csv = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
