[alias]
c = "check --workspace --all-targets --all-features --tests"
t = "nextest run --workspace --all-targets --all-features --no-fail-fast"
f = "fmt --all"
cl = "clippy --all-targets --all-features"
