[package]
name = "fs-store"
version = "0.1.0"
edition = "2024"

[dependencies]
kivis = { version = "0.3.0" }
serde = { workspace = true }
hex = { workspace = true }

[dev-dependencies]
anyhow = "1.0.100"
